name: Greeting from Mona

on:
  - push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Print a greeting
        if: github.action == 'closed' && github.pull_request.merged == 'true'
        run: |
          npm install
          echo "hihi"
