name: Greeting from Mona

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Print a greeting
        run: |
          npm install
          echo "hihi"
